### ISSUE TITLE
Development set up

### ISSUE THREAD

**Issue by axel1200** [web-cat/code-workout#168]
The development set up works fine there is only one issue. It requires a SSL certificate which one would need to self sign for development I guess. Anyways for development http is probably the better option anways.

```
web_1      | bundler: failed to load command: thin (/usr/local/bundle/bin/thin)
web_1      | EventMachine::FileNotFoundException: Could not find server.key for start_tls
web_1      |   /usr/local/bundle/gems/eventmachine-1.2.7/lib/em/connection.rb:430:in `block in start_tls'
web_1      |   /usr/local/bundle/gems/eventmachine-1.2.7/lib/em/connection.rb:428:in `each'
web_1      |   /usr/local/bundle/gems/eventmachine-1.2.7/lib/em/connection.rb:428:in `start_tls'
web_1      |   /usr/local/bundle/gems/thin-1.7.2/lib/thin/backends/base.rb:152:in `initialize_connection'
web_1      |   /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:1527:in `event_callback'
web_1      |   /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
web_1      |   /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
web_1      |   /usr/local/bundle/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
web_1      |   /usr/local/bundle/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
web_1      |   /usr/local/bundle/gems/thin-1.7.2/lib/thin/controllers/controller.rb:87:in `start'
web_1      |   /usr/local/bundle/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
web_1      |   /usr/local/bundle/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
web_1      |   /usr/local/bundle/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
web_1      |   /usr/local/bundle/bin/thin:29:in `load'
web_1      |   /usr/local/bundle/bin/thin:29:in `<top (required)>'
```

I just edited the runservers.sh to drop ssl.

root@265448d3e90c:/code-workout# cat runservers.sh 
bundle exec thin start -p 9292 --debug

Since you have a branch for development setup I think. Maybe you want to delete the ssl parameters their or otherwise we should probably include some kind of instruction to the read me on how to circumvent this.

**Comment by ayaankazerouni** [comment]
I think I'll include an instruction to create a self-signed certificate in the README. The certificate is needed if you want to embed a development instance of CodeWorkout in the [public Canvas site](canvas.instructure.com), e.g., to test the integration, even if it's self-signed.
